### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by ChrisChross** [ichise-lab/uwkgm#3]
Hi Developers,

first of all, thanks for this great library and platform! 

I am about to install the platform as descirbed in the README.md
when following error occurs:

/opt/anaconda3/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 37, in <module>
    raise ImproperlyConfigured('mysqlclient 1.3.13 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.9.3.

I am not sure if it because of my system or something.
In the requirements.txt it says: PyMySQL==0.9.3 and mysqlclient==1.4.6. 
I am using MacOS and i guess it has something todo with the use of pymqsql but not sure what exactly is the problem here.
Do you have any idea how to fix this?

Thanks for your help in advance. 
Chris

**Comment by rungsiman** [comment]
Hi Chris,

Thanks for your interest in our platform. We also encountered this problem before and it's Django's MySQL client that causes it. We were able to solve this problem by following the accepted answer in:
https://stackoverflow.com/questions/55657752/django-installing-mysqlclient-error-mysqlclient-1-3-13-or-newer-is-required

Rungsiman

**Comment by ChrisChross** [comment]
I went through this as well, yet it did not help for me. 
Though i just updated the version in the requirements.txt manually and set it to: 0.10.1 since pypi dont seem to have the version anymore. Thanks for your fast reply! I am eager to try it out now :)
